// Generated by CoffeeScript 1.3.3
(function() {
  var func, sum, times,
    __slice = [].slice;

  func = function() {
    return "bar";
  };

  times = function(a, b) {
    if (a == null) {
      a = 5;
    }
    if (b == null) {
      b = 7;
    }
    return a * b;
  };

  sum = function() {
    var nums, result;
    nums = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    result = 0;
    nums.foreach(function(n) {
      return result += n;
    });
    return result;
  };

}).call(this);
